name: Conda
on:
  push:
    branches: dev
jobs:
  Conda:
    runs-on: ubuntu-latest
    steps:
      - name: Grayskull
        run: pip install grayskull
      - name: Meta
        run: |
          grayskull pypi conspire
          cd conspire/
      - name: Conda
        run: conda install anaconda-client conda-build -y
      - name: Build
        run: conda build conspire
      - name: Upload
        run: |
          PATH="/usr/share/miniconda/bin/:$PATH"
          anaconda upload --token ${{ secrets.ANACONDA_TOKEN }} conspire
