name: Conda
on:
  pull_request:
    branches: main
  release:
    types: published
jobs:
  Conda:
    runs-on: ubuntu-latest
    steps:
      - name: Requirements
        run: pip install --upgrade grayskull maturin pip
      - name: Meta
        run: |
          grayskull pypi conspire
          cd conspire/
      - name: Conda
        run: conda install anaconda-client conda-build -y
      - name: Build
        run: conda build conspire
      - name: Upload
        if: github.event_name == 'release'
        run: |
          PATH="/usr/share/miniconda/bin/:$PATH"
          export ANACONDA_API_TOKEN=${{ secrets.ANACONDA_TOKEN }}
          anaconda upload --user mrbuche --force /usr/share/miniconda/conda-bld/noarch/conspire*.tar.bz2
