name: Docker
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref }}
env:
  CARGO_TERM_COLOR: always
on:
  pull_request:
    branches: main
  push:
    branches: main
  release:
    types: published
jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        id: last_release
        uses: InsonusK/get-latest-release@v1.1.0
        with:
          myToken: ${{ github.token }}
          view_top: 1
      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}
      - name: Build (latest)
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: mrbuche/conspire:latest
      - name: Test (latest)
        run: docker run --rm mrbuche/conspire:latest julia -e 'using Pkg; Pkg.test("Conspire")' && pytest /usr/conspire/python/
      - name: Build (stable)
        uses: docker/build-push-action@v6
        with:
          build-args: VERSION=${{ steps.last_release.outputs.tag_name }}
          load: true
          tags: mrbuche/conspire:${{ steps.last_release.outputs.tag_name }}
      - name: Julia (stable)
        run: docker run --rm mrbuche/conspire:${{ steps.last_release.outputs.tag_name }} julia -e 'using Pkg; Pkg.test("Conspire")'
      - name: Python (stable)
        run: docker run --rm mrbuche/conspire:${{ steps.last_release.outputs.tag_name }} pytest /usr/conspire/python/
      - name: Push (latest)
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mrbuche/conspire:latest
      - name: Push (stable)
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v6
        with:
          build-args: VERSION=${{ steps.last_release.outputs.tag_name }}
          push: true
          tags: mrbuche/conspire:${{ steps.last_release.outputs.tag_name }}
