name: Book
on:
  pull_request:
    branches: main
  push:
    branches: main
env:
  CARGO_TERM_COLOR: always
jobs:
  Book:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        id: last_release
        uses: InsonusK/get-latest-release@v1.1.0
        with:
          myToken: ${{ github.token }}
          view_top: 1
      - name: Rust
        uses: actions-rs/toolchain@v1
        with:
          default: true
          toolchain: stable
      - name: Dependencies
        run: cargo install mdbook mdbook-cmdrun mdbook-katex
      - name: Checkout (stable)
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.last_release.outputs.tag_name }}
          submodules: true
      - name: Stable
        run: |
          pip install conspire==${{ steps.last_release.outputs.tag_name }} matplotlib numpy
          mdbook build
          grep -lr "julia.html" book/build/ | xargs sed -i 's@href="julia.html"@href="https://mrbuche.github.io/Conspire.jl"@'
          grep -lr "python.html" book/build/ | xargs sed -i 's@href="python.html"@href="https://conspire.readthedocs.io"@'
          grep -lr "rust.html" book/build/ | xargs sed -i 's@href="rust.html"@href="https://docs.rs/conspire"@'
          mkdir -p ../_site/stable/ && cp -r book/build/* ../_site/stable/
      - name: Checkout (latest)
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Latest
        run: |
          pip install git+https://github.com/mrbuche/conspire.py.git matplotlib numpy
          mdbook build
          grep -lr "julia.html" book/build/ | xargs sed -i 's@href="julia.html"@href="https://mrbuche.github.io/Conspire.jl/latest"@'
          grep -lr "python.html" book/build/ | xargs sed -i 's@href="python.html"@href="https://conspire.readthedocs.io/en/latest"@'
          grep -lr "rust.html" book/build/ | xargs sed -i 's@href="rust.html"@href="https://mrbuche.github.io/conspire.rs/latest"@'
          mkdir -p ../_site/latest/ && cp -r book/build/* ../_site/latest/
      - name: Site
        run: cp book/redirect.html ../_site/index.html
      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: ../_site/
  Deploy:
    if: github.event_name != 'pull_request'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: Book
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
