name: Book
on:
  pull_request:
    branches: main
  push:
    branches: main
env:
  CARGO_TERM_COLOR: always
jobs:
  Book:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          default: true
          toolchain: stable
      - name: mdbook
        run: cargo install mdbook mdbook-cmdrun mdbook-katex
      - name: build
        run: mdbook build
      - name: move
        run: mkdir -p _site/ && cp -r book/build/* _site/
      - name: upload
        uses: actions/upload-pages-artifact@v3
  Deploy:
    if: github.event_name != 'pull_request'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: Book
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
